[pytest]
markers =
    verify_item_count: test to make sure the cart shows the correct number of items
    reset: test that verifies the cart resets to empty state
    logout: test that verifies logout
    validlogin: test that verifies login with valid credential
    login_button: verifies the text in login button
    verify_sorting: verifies sorting